### ISSUE TITLE
jup-ag/core package throws error while importing in react js (craco)

### ISSUE THREAD

**Issue by mohan00710** [jup-ag/feedback#1]
./node_modules/@jup-ag/core/dist/core.esm.js 1384:73
Module parse failed: Unexpected token (1384:73)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   remainingAccounts.push(...prepareRemainingAccounts(amount, platformFee?.feeAccount));
|   return JUPITER_PROGRAM.instruction.mercurialExchange(amount ? new BN$1(amount) : amount, new BN$1(minimumOutAmount), platformFee?.feeBps ?? 0, {
|     accounts: stableSwapNPoolIntoMercurialExchange(stableSwapNPool, userSourceTokenAccountAddress, userDestinationTokenAccountAddress, user),

![image](https://user-images.githubusercontent.com/57178922/149765972-3bb0f298-403d-4018-942d-1fc294514785.png)

please fix this .this is the link (https://discord.com/channels/897540204506775583/910250162402779146/927391710311481384 ) suggested by a dev in you discord group..this might be helpfull in solving

**Comment by ZhengYuTay** [comment]
resolved
https://discord.com/channels/897540204506775583/910250162402779146/932607531786842132

**Comment by mohan00710** [comment]
the solution above solved the err that was in console...but new err got showed up in the browser

![image](https://user-images.githubusercontent.com/57178922/149885321-985bfb46-5749-4cb6-b9fc-7e1479d16a34.png)
